services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=daniel.alyoshin@mail.utoronto.ca

  backend:
    image: docker.io/danielalyoshin/lada-core:latest
    ports:
      - '4000:4000'
    restart: always
    expose:
      - 4000
    environment:
      - VIRTUAL_HOST=api.ladaland.com
      - LETSENCRYPT_HOST=api.ladaland.com
      - GCLOUD_PROJECT_ID=vast-collective-454403-n7
      - GCLOUD_STORAGE_BUCKET=lada-bucket
      - GCLOUD_KEYFILE=/run/secrets/gcloud_key.json
    volumes:
      - /home/daniel.alyoshin/secure-keys/gcloud_key.json:/run/secrets/gcloud_key.json:ro

  frontend:
    image: docker.io/danielalyoshin/lada-client:latest
    ports:
      - '3000:3000'
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=ladaland.com
      - LETSENCRYPT_HOST=ladaland.com

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ladaadmin
      POSTGRES_PASSWORD: ladaadmin4567!
      POSTGRES_DB: ladaland
    ports:
      - '5555:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
