name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install --prefix core

          npm install --prefix client --legacy-peer-deps

      - name: Create .env file for core
        run: |
          echo "${{ secrets.CORE_ENV }}" > core/.env

      - name: Create .env file for client
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > client/.env

      - name: Run tests
        run: npm run test --prefix core

      - name: Build core docker image
        run: docker build -t danielalyoshin/lada-core:latest -f core/Dockerfile .

      - name: Build client docker image
        run: docker build -t danielalyoshin/lada-client:latest -f client/Dockerfile .

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push docker images to Docker Hub
        run: |
          docker push danielalyoshin/lada-core:latest
          docker push danielalyoshin/lada-client:latest

      - name: SSH into VM and pull docker images and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull danielalyoshin/lada-core:latest
            sudo docker pull danielalyoshin/lada-client:latest
            sudo docker compose -f docker-compose.prod.yml up -d
